name: flutter_critical_alert_permission_ios
description: Request critical alerts on iOS directly from Dart code.
version: 0.1.0
homepage: https://github.com/lucaspal/flutter_critical_alert_permission_ios.git

environment:
  sdk: '>=2.12.0 <3.8.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCriticalAlertPermissionIosPlugin
