name: flutter_critical_alert_permission_ios
description: Request critical alerts on iOS directly from Dart code.
version: 0.0.1
author: Luca Spalierno
homepage: https://www.spalierno.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCriticalAlertPermissionIosPlugin
